[package]
name = "serial2-async-std"
version = "0.0.0"
description = "placeholder for upcoming async-std version of serial2"
license = "BSD-2-Clause OR Apache-2.0"
repository = "https://github.com/de-vri-es/serial2-async-std-rs"

publish = ["crates-io"]
edition = "2021"

[dependencies]
